"""
Blind Corner Alert System — Vehicle Detection Pipeline
========================================================
Pi 5 side software: reads video (CP Plus camera stream or a video file),
runs YOLO11 detection with ByteTrack, and raises an ALERT the moment any
person/vehicle/cyclist is present inside the configured ROI (if any) — which
would be sent to the Arduino Nano over serial to fire the relay.

Usage:
    python3 detect.py --source dummy_corner.mp4 --out annotated_output.mp4
    python3 detect.py --source rtsp://<cp-plus-camera-ip>/stream1   # live camera
    python3 detect.py --source 0                                    # USB webcam

Requires: ultralytics, opencv-python, torch, lap (for ByteTrack)
    pip install -U ultralytics opencv-python lap

Tracker config: expects custom_bytetrack.yaml in the same folder — a copy of
ultralytics' default bytetrack.yaml with fuse_score explicitly set to True.

ROI (optional): if roi_points.json (generated by set_roi.py) is present next
to this script, only detections inside that polygon trigger an alert. Without
it, ANY detection anywhere in frame triggers STOP — fine for a tightly framed
camera, but for a wide-angle CCTV view you almost certainly want an ROI, or
you'll alert on traffic that has nothing to do with the blind corner.
"""

import argparse
import json
import math
import os
import time
from collections import deque

import cv2
import numpy as np
from ultralytics import YOLO

# ----------------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------------

# COCO class ids for everything we want to alert on (from the pretrained YOLO11 model).
# Expanded from vehicles-only: a blind-corner alert also needs pedestrians and
# cyclists, since those are exactly as invisible to a reversing driver.
#
# NOTE on coverage — this is the pretrained COCO class set, it does NOT have
# separate classes for everything you might see on an Indian street:
#   - "scooty" / scooters / mopeds -> fall under class 3 "motorcycle" (COCO
#     doesn't distinguish scooter vs motorcycle body styles, both map here)
#   - auto-rickshaws / tuk-tuks -> NO dedicated COCO class exists. The stock
#     model will inconsistently call these "car", sometimes "motorcycle", and
#     will sometimes miss them entirely, especially from the side. Reliable
#     auto-rickshaw detection needs a model fine-tuned on Indian road data
#     (e.g. the IDD — India Driving Dataset — which has an explicit
#     "autorickshaw" class) rather than stock yolo11n/COCO weights.
ALERT_CLASSES = {0: "person", 1: "bicycle", 2: "car", 3: "motorcycle", 5: "bus", 7: "truck"}

MOVEMENT_THRESHOLD_PX = 8       # min centroid displacement (px) between frames — used only for the
                                 # on-screen "MOVING"/"static" label now, no longer gates the alert
HISTORY_LEN = 8                 # compare centroid against ~this many frames ago instead of just the
                                 # previous frame, so slow-but-continuous motion accumulates enough
                                 # displacement to register as MOVING instead of flickering
CONF_THRESHOLD = 0.25           # lowered from 0.35 — pedestrians/two-wheelers are smaller, harder
                                 # targets than cars; the ROI + hold-frame debounce absorb the extra
                                 # noise from the lower threshold
ALERT_HOLD_FRAMES = 15          # keep alert ON for N frames after last detection (debounce)
TRACKER_CFG = "custom_bytetrack.yaml"  # local file (copy of ultralytics' bytetrack.yaml with fuse_score fix) — must sit next to this script
ROI_FILE = "roi_points.json"    # optional — generated by set_roi.py; if absent, no ROI filtering is applied


class SafetyState:
    SAFE = "SAFE"
    STOP = "STOP"  # alert active -> relay/LED on


# ----------------------------------------------------------------------------
# ROI helpers (same as set_roi.py / run_on_my_video.py)
# ----------------------------------------------------------------------------
def load_roi_polygon(roi_file):
    """Load ROI polygon from JSON file. Returns numpy array of points or None."""
    if not os.path.exists(roi_file):
        print(f"⚠️  No ROI file found ({roi_file}) — running WITHOUT ROI filter, "
              f"every detection in frame will count. Run set_roi.py to scope this to your blind corner.\n")
        return None

    with open(roi_file, 'r') as f:
        data = json.load(f)

    points = data.get("roi_polygon", [])
    if len(points) < 3:
        print(f"⚠️  ROI polygon in {roi_file} has fewer than 3 points — ignoring.")
        return None

    polygon = np.array(points, dtype=np.int32)
    print(f"✅ ROI polygon loaded from {roi_file} ({len(points)} vertices)")
    return polygon


def point_in_polygon(cx, cy, polygon):
    """Check if a point (cx, cy) is inside the polygon using OpenCV."""
    result = cv2.pointPolygonTest(polygon.astype(np.float32), (float(cx), float(cy)), False)
    return result >= 0  # >= 0 means inside or on edge


# ----------------------------------------------------------------------------
# Serial relay stub — mirrors the report's SerialRelayController.
# On the real Pi 5 + Arduino Nano setup, swap this for pyserial writes to
# /dev/ttyACM0 (Arduino Nano over USB).
# ----------------------------------------------------------------------------
class RelayController:
    def __init__(self, port=None, enabled=False):
        self.enabled = enabled
        self.port = port
        self._serial = None
        if enabled:
            try:
                import serial  # pyserial
                self._serial = serial.Serial(port, 9600, timeout=1)
                print(f"[Relay] Connected to Arduino on {port}")
            except Exception as e:
                print(f"[Relay] Could not open {port} ({e}) — running in simulation mode")
                self.enabled = False

    def set_state(self, state: str):
        if self.enabled and self._serial:
            self._serial.write(b"1\n" if state == SafetyState.STOP else b"0\n")
        # simulation / logging mode always prints so you can see it working
        # without hardware attached
        print(f"[Relay] -> {state}", end="\r")


# ----------------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------------
def run(source, out_path, model_name="yolo11n.pt", relay_port=None, use_relay=False, show=False):
    print("Loading YOLO11 model...")
    model = YOLO(model_name)

    cap = cv2.VideoCapture(int(source) if str(source).isdigit() else source)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video source: {source}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 20
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    roi_polygon = load_roi_polygon(ROI_FILE)
    use_roi = roi_polygon is not None

    writer = None
    if out_path:
        writer = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

    relay = RelayController(port=relay_port, enabled=use_relay)

    # ByteTrack gives us persistent IDs across frames. For each track we keep
    # a short rolling history of centroids (deque(maxlen=HISTORY_LEN)) instead
    # of just the last position, so the "MOVING"/"static" label is judged over
    # several frames of displacement rather than one noisy frame-to-frame diff.
    track_history: dict[int, deque] = {}
    hold_timer = 0
    state = SafetyState.SAFE
    prev_state = SafetyState.SAFE
    frame_idx = 0
    alert_events = []

    t0 = time.time()
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        frame_idx += 1

        # persist=True keeps ByteTrack's internal track state alive between
        # calls on this same `model` instance — that's what makes IDs stable
        # across frames instead of resetting every call.
        results = model.track(
            frame,
            persist=True,
            tracker=TRACKER_CFG,
            verbose=False,
            conf=CONF_THRESHOLD,
        )[0]

        # `any_object_present` drives the SAFE/STOP decision: for a blind-corner
        # alert, something simply BEING in the ROI is the hazard — waiting a
        # frame or two to confirm "motion" defeats the point of the warning.
        any_object_present = False
        boxes = results.boxes
        ids = boxes.id.int().cpu().tolist() if boxes.id is not None else [None] * len(boxes)

        for box, tid in zip(boxes, ids):
            cls_id = int(box.cls[0])
            if cls_id not in ALERT_CLASSES:
                continue
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            conf = float(box.conf[0])
            cx, cy = (x1 + x2) / 2, (y1 + y2) / 2

            if use_roi and not point_in_polygon(cx, cy, roi_polygon):
                cv2.rectangle(frame, (x1, y1), (x2, y2), (128, 128, 128), 1)
                cv2.putText(frame, "outside ROI", (x1, max(20, y1 - 8)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.4, (128, 128, 128), 1)
                continue

            any_object_present = True

            # Compare against the OLDEST centroid in this track's history
            # window (~HISTORY_LEN frames ago) rather than just the previous
            # frame — slow-but-continuous motion accumulates enough
            # displacement over that window to clear MOVEMENT_THRESHOLD_PX
            # reliably, instead of flickering MOVING/static frame to frame.
            moving = False
            if tid is not None:
                hist = track_history.setdefault(tid, deque(maxlen=HISTORY_LEN))
                if len(hist) == HISTORY_LEN:
                    px, py = hist[0]
                    moving = math.hypot(cx - px, cy - py) > MOVEMENT_THRESHOLD_PX
                hist.append((cx, cy))

            # draw
            id_label = f"id{tid}" if tid is not None else "id?"
            label = f"{ALERT_CLASSES[cls_id]} {id_label} {conf:.2f} {'MOVING' if moving else 'static'}"
            color = (0, 0, 255) if moving else (0, 200, 0)
            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
            cv2.putText(frame, label, (x1, max(20, y1 - 8)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        # drop stale entries for tracks that ByteTrack itself has already dropped
        active_ids = {tid for tid in ids if tid is not None}
        track_history = {tid: h for tid, h in track_history.items() if tid in active_ids}

        # --- decision logic ---
        if any_object_present:
            hold_timer = ALERT_HOLD_FRAMES
            state = SafetyState.STOP
        elif hold_timer > 0:
            hold_timer -= 1
            state = SafetyState.STOP
        else:
            state = SafetyState.SAFE

        # Only log a new alert event on the SAFE -> STOP transition, not just
        # because time has elapsed since the last logged event — an elapsed-time
        # check re-fires repeatedly during one continuous STOP period, inflating
        # the event count.
        if state == SafetyState.STOP and prev_state == SafetyState.SAFE:
            alert_events.append(frame_idx)
        prev_state = state

        relay.set_state(state)

        # overlay status banner
        banner_color = (0, 0, 255) if state == SafetyState.STOP else (0, 180, 0)
        cv2.rectangle(frame, (0, 0), (260, 40), banner_color, -1)
        cv2.putText(frame, f"STATUS: {state}", (10, 27),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

        if writer:
            writer.write(frame)
        if show:
            cv2.imshow("Blind Corner Alert - Debug View", frame)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break

    elapsed = time.time() - t0
    cap.release()
    if writer:
        writer.release()
    if show:
        cv2.destroyAllWindows()

    print(f"\nProcessed {frame_idx} frames in {elapsed:.1f}s ({frame_idx/elapsed:.1f} FPS)")
    print(f"Alert triggered {len(alert_events)} time(s) at frames: {alert_events}")
    if out_path:
        print(f"Annotated video saved to: {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Blind Corner Alert - YOLO11 + ByteTrack detection")
    parser.add_argument("--source", default="dummy_corner.mp4",
                         help="Video file path, RTSP URL, or camera index (e.g. 0)")
    parser.add_argument("--out", default="annotated_output.mp4", help="Output annotated video path")
    parser.add_argument("--model", default="yolo11n.pt", help="YOLO11 model weights (nano = fastest, good for Pi)")
    parser.add_argument("--relay-port", default="/dev/ttyACM0", help="Serial port for Arduino Nano")
    parser.add_argument("--use-relay", action="store_true", help="Actually send serial signal to Arduino")
    parser.add_argument("--show", action="store_true", help="Show live debug window (needs display)")
    args = parser.parse_args()

    run(args.source, args.out, args.model, args.relay_port, args.use_relay, args.show)